spring.application.name=api-user
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dmh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8081}
spring.config.import=optional:configserver:instead
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:true}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/dmh-realm}
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:dmh-realm}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:api-user}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}